# Generated by Django 2.1.5 on 2020-04-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsusers',
            options={'verbose_name': 'NewsUser', 'verbose_name_plural': 'NewsUsers'},
        ),
    ]
